### ISSUE TITLE
Atom S3 with relay board

### ISSUE THREAD

**Issue by rlust** [m5stack/UNIT_4RELAY#1]
### Describe the bug

I need an example program to use the 4 Relay board with an AtomS3 board

### To reproduce

OSX

### Expected behavior

Example from to use Atom S3 with grove connecTed 4 relay board

### Environment

- OS: Mac
- IDE &IDE Version: 2.2.1
- Repository Version:

### Additional context

1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Family/issues?q=)
- [X] My report contains all necessary details

**Comment by TinyuZhao** [comment]
Added.
https://github.com/m5stack/M5Unit-RELAY/commit/f66e9fb5d86128c367755102447e8b743e4050e7
