### ISSUE TITLE
M5Atom with 4-Relay Unit

### ISSUE THREAD

**Issue by kz1000a1** [m5stack/UNIT_4RELAY#2]
### Describe the bug

examples/Unit_4RELAY_M5Atom/Unit_4RELAY_M5Atom.ino
Default of M5Atom's M5.begin() is I2C enable.
Modify to M5.begin(true, false, false) or relay.begin(&Wire1, 26, 32) is needed.

### To reproduce

Build and run.

### Expected behavior

4-Relay Unit does not work properly.

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Family/issues?q=)
- [X] My report contains all necessary details

**Comment by gapaul** [comment]
In the example for Unit_4RELAY_M5Core2 I had a similar issue with the Unit_4Relay as you are having with your M5Atom. 

I solved it, basically as suggested above, by adding
        relay.begin();
before the call to 
        relay.Init(0);

Then, the example worked as expected. I didn't have to change the "M5.begin(" line in the example, nor anything in the underlying library Unit_4RELAY.cpp. 

If I didn't add this, the code crashes and restarts the ESP32 when doing _wire->write(Register_address) inside UNIT_4RELAY::write1Byte

I suspect it is the same issue as you (kz1000a1) are having.

**Comment by TinyuZhao** [comment]
Fixed.
https://github.com/m5stack/M5Unit-RELAY/commit/ed8abed2e5484650cf37fbb6758faa61c52ac036
